import { assertEquals, assertThrows } from '@std/assert'
import { describe, it } from 'node:test'
import { CliError } from '../utils/error.utils.ts'
import { parseConfig } from './config.ts'

const section = (tagline: unknown): string => JSON.stringify({ tagline })

describe('All Tagline Config Tests', () => {
  describe('parseConfig', () => {
    it('reads the tagline and the stale spellings a project gives', () => {
      // Arrange
      const text = section({ text: '> _Generated with Claude_', stale: ['_Generated by Claude_', '_generated by claude_'] })

      // Act
      const config = parseConfig(text)

      // Assert
      assertEquals(config, { text: '> _Generated with Claude_', stale: ['_Generated by Claude_', '_generated by claude_'] })
    })

    it('reads an absent stale list as none', () => {
      // Act
      const config = parseConfig(section({ text: '> _Generated with Claude_' }))

      // Assert
      assertEquals(config, { text: '> _Generated with Claude_', stale: [] })
    })

    it('refuses an absent tools.config.json, since the tagline is the project convention and has no default', () => {
      // Act & Assert
      assertThrows(() => parseConfig('{}'), CliError, 'text is required, since the tool has no tagline of its own')
    })

    it('refuses a section that sets no text, showing the shape to write', () => {
      // Act
      const error = assertThrows(() => parseConfig(section({ stale: ['_Generated by Claude_'] })), CliError, 'text is required')

      // Assert
      assertEquals(error.suggestions, ['Write it as { "tagline": { "text": "<the line every body ends with>", "stale": ["<an older spelling to strip>"] } }'])
    })

    it('refuses a file that is not JSON with its own suggestion, since the hook has no defaults to fall back to', () => {
      // Act
      const error = assertThrows(() => parseConfig('{ bad'), CliError, 'tools.config.json is not valid JSON')

      // Assert
      assertEquals(error.suggestions, ['Write it as { "tagline": { "text": "<the line every body ends with>", "stale": ["<an older spelling to strip>"] } }'])
    })

    it('refuses a misspelled key rather than reading the section as having no stale spellings', () => {
      // Act & Assert
      assertThrows(() => parseConfig(section({ text: '> _Generated with Claude_', stales: [] })), CliError, 'Unrecognized key: "stales"')
    })

    it('refuses an empty text, which every body would end with', () => {
      // Act & Assert
      assertThrows(() => parseConfig(section({ text: '' })), CliError, 'Too small')
    })

    it('refuses a text that is not a string as a wrong type rather than as a missing one', () => {
      // Act & Assert
      assertThrows(() => parseConfig(section({ text: 4 })), CliError, 'expected string, received number')
    })

    it('refuses a text ending in whitespace, which no trimmed body could end with', () => {
      // Act & Assert
      assertThrows(() => parseConfig(section({ text: '> _Generated with Claude_ ' })), CliError, 'must not start or end with whitespace')
    })

    it('refuses an empty stale spelling, which names nothing to strip', () => {
      // Act & Assert
      assertThrows(() => parseConfig(section({ text: '> _Generated with Claude_', stale: [''] })), CliError, 'Too small')
    })
  })
})
