import { assertEquals } from '@std/assert'
import { describe, it } from 'node:test'
import { type BodySource, findBodyWrites, type Finding, graphqlBodyMutationPattern, hasTagline, issueEndpointPattern, shellCommandFlagPattern, taglineSeparatorPattern } from './parser.ts'

const TAGLINE = '> _Generated with Claude_'

const writesIn = (command: string): Finding[] => findBodyWrites(command, '/work/p')

const sourcesOf = (command: string): BodySource[] => writesIn(command).flatMap((finding) => finding.sources)

const written = (value: string, flag: string): BodySource => ({ kind: 'written', value, flag, dynamic: false })

const runtime = (value: string, flag: string): BodySource => ({ kind: 'runtime', value, flag, dynamic: true })

const inline = (value: string, flag: string): BodySource => ({ kind: 'inline', value, flag, dynamic: false })

describe('All Tagline Parser Tests', () => {
  describe('hasTagline', () => {
    it('accepts a body ending with the tagline after a blank line', () => {
      // Act & Assert
      assertEquals(hasTagline(`## Summary\n\nSome prose.\n\n${TAGLINE}`, TAGLINE), true)
    })

    it('accepts a body with trailing whitespace after the tagline', () => {
      // Act & Assert
      assertEquals(hasTagline(`Prose.\n\n${TAGLINE}\n\n  \n`, TAGLINE), true)
    })

    it('accepts a body that is the tagline alone', () => {
      // Act & Assert
      assertEquals(hasTagline(TAGLINE, TAGLINE), true)
    })

    it('accepts a blank line written with carriage returns', () => {
      // Act & Assert
      assertEquals(hasTagline(`Prose.\r\n\r\n${TAGLINE}`, TAGLINE), true)
    })

    it('rejects a body with no tagline', () => {
      // Act & Assert
      assertEquals(hasTagline('## Summary\n\nSome prose.\n', TAGLINE), false)
    })

    it('rejects a tagline that is not the final line', () => {
      // Act & Assert
      assertEquals(hasTagline(`${TAGLINE}\n\nTrailing afterthought.`, TAGLINE), false)
    })

    it('rejects a stale lowercase variant of the tagline', () => {
      // Act & Assert
      assertEquals(hasTagline('Prose.\n\n> _generated by claude_', TAGLINE), false)
    })

    it('rejects a tagline on the same line as the prose', () => {
      // Act & Assert
      assertEquals(hasTagline(`prose ${TAGLINE}`, TAGLINE), false)
    })

    it('rejects a tagline on the next line with no blank line before it', () => {
      // Act & Assert
      assertEquals(hasTagline(`Prose.\n${TAGLINE}`, TAGLINE), false)
    })
  })

  describe('findBodyWrites on the body-writing subcommands', () => {
    it('reads the body of an issue comment, keeping the segment and subcommand', () => {
      // Act
      const findings = writesIn(`git status && gh issue comment 4 --body 'text' && echo ok`)

      // Assert
      assertEquals(findings, [{ segment: "gh issue comment 4 --body 'text'", subcommand: 'issue comment', sources: [inline('text', '--body')] }])
    })

    it('reads the body of an issue edit', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh issue edit 4 --body x'), [inline('x', '--body')])
    })

    it('reads the comment of an issue reopen', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh issue reopen 4 --comment x'), [inline('x', '--comment')])
    })

    it('reads the comment of an issue close by its short flag', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh issue close 8 -c done'), [inline('done', '-c')])
    })

    it('reads the body of a pr edit', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh pr edit 3 --body x'), [inline('x', '--body')])
    })

    it('reads the comment of a pr close', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh pr close 3 --comment x'), [inline('x', '--comment')])
    })

    it('reads the comment of a pr reopen by its short flag', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh pr reopen 3 -c x'), [inline('x', '-c')])
    })

    it('reads the body of a pr review, where -c is the comment switch rather than a value', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh pr review 3 -cbhi'), [inline('hi', '-b')])
    })

    it('reads the body of an issue or a pr created through the new alias', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh pr new --body x'), [inline('x', '--body')])
      assertEquals(sourcesOf('gh issue new --body x'), [inline('x', '--body')])
    })

    it('reads the notes of a release create', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh release create v1 --notes x'), [inline('x', '--notes')])
    })

    it('reads the notes file of a release edit', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh release edit v1 --notes-file /tmp/n.md'), [{ kind: 'file', value: '/tmp/n.md', flag: '--notes-file', dynamic: false }])
    })

    it('reads release notes by their short flags', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh release create v1 -n x -F /tmp/n.md'), [inline('x', '-n'), { kind: 'file', value: '/tmp/n.md', flag: '-F', dynamic: false }])
    })

    it('ignores gist create, which carries no body flag', () => {
      // Act & Assert
      assertEquals(writesIn('gh gist create --desc x notes.md'), [])
    })

    it('ignores read-only and body-free gh commands', () => {
      // Act & Assert
      assertEquals(writesIn('gh issue list --label bug && gh issue view 4 && gh issue close 12 && gh issue edit 12 --add-label "P1: high"'), [])
    })
  })

  describe('findBodyWrites on flag spellings', () => {
    it('reads the short body flag', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh issue comment 4 -b hi'), [inline('hi', '-b')])
    })

    it('reads a short body flag with its value attached', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh issue comment 4 -bhi'), [inline('hi', '-b')])
    })

    it('reads a short body flag after boolean switches in one cluster', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh pr create -db hi'), [inline('hi', '-b')])
    })

    it('reads past a short flag whose value is attached, rather than reading the value as flags', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh issue create -tbug -b hi'), [inline('hi', '-b')])
    })

    it('reads the word after a value-taking short flag as its value, even one spelled like a body flag', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh issue create -t "--body" -b hi'), [inline('hi', '-b')])
    })

    it('reads the long body flag with an equals sign', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh issue comment 4 --body=hi'), [inline('hi', '--body')])
    })

    it('reads the long comment flag with an equals sign', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh issue close 8 --comment=done'), [inline('done', '--comment')])
    })

    it('reads the long body file flag with an equals sign', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh issue create --body-file=/tmp/b.md'), [{ kind: 'file', value: '/tmp/b.md', flag: '--body-file', dynamic: false }])
    })

    it('reads -F on an issue command as the body file', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh issue create -F /tmp/b.md'), [{ kind: 'file', value: '/tmp/b.md', flag: '-F', dynamic: false }])
    })

    it('reads -F with its path attached', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh pr comment 3 -F/tmp/b.md'), [{ kind: 'file', value: '/tmp/b.md', flag: '-F', dynamic: false }])
    })

    it('reads -F - on a pr command as a stdin body', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh pr create -F -'), [{ kind: 'stdin', value: '-', flag: '-F', dynamic: false }])
    })

    it('reads --body-file - as a stdin body', () => {
      // Act & Assert
      assertEquals(sourcesOf('cat /tmp/b.md | gh issue create --body-file -'), [{ kind: 'stdin', value: '-', flag: '--body-file', dynamic: false }])
    })

    it('reads the subcommand after a short repo flag before it', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh -R owner/repo issue create --body x'), [inline('x', '--body')])
    })

    it('reads the subcommand after a long repo flag before it, in either spelling', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh --repo o/r pr comment 3 --body x'), [inline('x', '--body')])
      assertEquals(sourcesOf('gh --repo=o/r pr comment 3 --body x'), [inline('x', '--body')])
    })
  })

  describe('findBodyWrites on gh api', () => {
    it('reads a body field file on a PATCH', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh api -X PATCH repos/o/r/issues/comments/5 -F body=@/tmp/b.md'), [{ kind: 'file', value: '/tmp/b.md', flag: '-F body', dynamic: false }])
    })

    it('treats fields with no method as a POST', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh api repos/o/r/issues/1/comments -f body=hi'), [inline('hi', '-f body')])
    })

    it('reads the method from its long flag', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh api --method PATCH repos/o/r/issues/1 --raw-field body=hi'), [inline('hi', '--raw-field body')])
    })

    it('reads the method and fields in their attached spellings', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh api --method=PATCH repos/o/r/issues/1 -fbody=hi'), [inline('hi', '-f body')])
      assertEquals(sourcesOf('gh api -XPOST repos/o/r/issues/1/comments --field=body=hi'), [inline('hi', '--field body')])
      assertEquals(sourcesOf('gh api -iXPOST repos/o/r/issues/1/comments -F body=hi'), [inline('hi', '-F body')])
    })

    it('reads an endpoint written after the fields', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh api -f body=hi repos/o/r/pulls/2/comments'), [inline('hi', '-f body')])
    })

    it('reads a raw field starting with @ as literal text rather than a file', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh api repos/o/r/issues/1/comments -f body=@notes.md'), [inline('@notes.md', '-f body')])
    })

    it('reads body=@- as a stdin body', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh api repos/o/r/issues/1/comments -F body=@-'), [{ kind: 'stdin', value: '-', flag: '-F body', dynamic: false }])
    })

    it('reads an input file as JSON to check, and - as a stdin body', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh api repos/o/r/issues --input /tmp/issue.json'), [{ kind: 'json-file', value: '/tmp/issue.json', flag: '--input', dynamic: false }])
      assertEquals(sourcesOf('gh api repos/o/r/issues --input=-'), [{ kind: 'stdin', value: '-', flag: '--input', dynamic: false }])
    })

    it('reads a body sent to a releases endpoint', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh api repos/o/r/releases -f tag_name=v1 -f body=hi'), [inline('hi', '-f body')])
    })

    it('reads a body sent to a commit comment endpoint, new or edited', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh api repos/o/r/commits/abc123/comments -f body=hi'), [inline('hi', '-f body')])
      assertEquals(sourcesOf('gh api -X PATCH repos/o/r/comments/7 -f body=hi'), [inline('hi', '-f body')])
    })

    it('ignores a GET however its method is spelled', () => {
      // Act & Assert
      assertEquals(writesIn('gh api repos/o/r/issues/1'), [])
      assertEquals(writesIn('gh api -X get repos/o/r/issues -f body=x'), [])
      assertEquals(writesIn('gh api --method GET repos/o/r/issues -f state=open'), [])
    })

    it('ignores a POST with a body to an endpoint that carries no issue, pull request, release, or comment prose', () => {
      // Act & Assert
      assertEquals(writesIn('gh api repos/o/r/git/tags -f body=x'), [])
    })

    it('ignores fields other than body', () => {
      // Act & Assert
      assertEquals(writesIn('gh api -X PATCH repos/o/r/issues/1 -F state=closed'), [])
    })
  })

  describe('findBodyWrites on gh api graphql', () => {
    it('reads a mutation passing a body as uncheckable', () => {
      // Arrange
      const query = 'mutation { addComment(input: {subjectId: "x", body: "hi"}) { clientMutationId } }'

      // Act & Assert
      assertEquals(sourcesOf(`gh api graphql -f query='${query}'`), [{ kind: 'graphql', value: query, flag: '-f query', dynamic: false }])
    })

    it('ignores a query that writes nothing', () => {
      // Act & Assert
      assertEquals(writesIn(`gh api graphql -f query='query { viewer { login } }'`), [])
    })

    it('reads a query file and an input file for the checker to inspect', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh api graphql -F query=@q.graphql'), [{ kind: 'graphql-file', value: 'q.graphql', flag: '-F query', dynamic: false }])
      assertEquals(sourcesOf('gh api graphql --input q.json'), [{ kind: 'graphql-file', value: 'q.json', flag: '--input', dynamic: false }])
    })

    it('reads a query built at run time as uncheckable', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh api graphql -f query="$Q"'), [{ kind: 'runtime', value: '$Q', flag: '-f query', dynamic: true }])
    })
  })

  describe('findBodyWrites on bodies built at run time', () => {
    it('marks a body holding a command substitution as dynamic', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh issue comment 4 --body "$(git log -1)"'), [{ kind: 'inline', value: '$(git log -1)', flag: '--body', dynamic: true }])
    })

    it('marks a body file path holding a variable as built at run time', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh issue create --body-file "$TMP/b.md"'), [{ kind: 'runtime', value: '$TMP/b.md', flag: '--body-file', dynamic: true }])
    })

    it('unwraps a quoted cat heredoc to its literal text', () => {
      // Act & Assert
      assertEquals(sourcesOf(`gh issue create --body "$(cat <<'EOF'\nSummary line\n\n${TAGLINE}\nEOF\n)"`), [inline(`Summary line\n\n${TAGLINE}`, '--body')])
    })

    it('marks an unquoted cat heredoc that expands a variable as dynamic', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh issue create --body "$(cat <<EOF\nFixed $SHA\nEOF\n)"'), [{ kind: 'inline', value: 'Fixed $SHA', flag: '--body', dynamic: true }])
    })

    it('ends a heredoc at a terminator line with whitespace around it', () => {
      // Act & Assert
      assertEquals(sourcesOf(`gh issue create --body "$(cat <<'EOF'\nProse.\n  EOF  \n)"`), [inline('Prose.', '--body')])
    })

    it('decodes an ANSI-C quoted body', () => {
      // Act & Assert
      assertEquals(sourcesOf(`gh pr comment 1 --body $'Prose.\\n\\n${TAGLINE}'`), [inline(`Prose.\n\n${TAGLINE}`, '--body')])
    })

    it('reads the escapes inside double quotes as the characters they stand for', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh pr comment 1 --body "say \\"hi\\" for \\$5"'), [inline('say "hi" for $5', '--body')])
    })

    it('joins a line continued with a backslash', () => {
      // Act & Assert
      assertEquals(sourcesOf('gh issue comment 1 --body \\\n  x'), [inline('x', '--body')])
    })
  })

  describe('findBodyWrites on where gh runs', () => {
    it('finds gh after variable assignments', () => {
      // Act & Assert
      assertEquals(sourcesOf('GH_REPO=o/r GH_HOST=x gh issue comment 1 --body x'), [inline('x', '--body')])
    })

    it('finds gh after env with its options and assignments', () => {
      // Act & Assert
      assertEquals(sourcesOf('env -i -u FOO GH_REPO=x gh issue comment 1 --body x'), [inline('x', '--body')])
    })

    it('finds gh after command and exec', () => {
      // Act & Assert
      assertEquals(sourcesOf('command gh issue comment 1 --body x'), [inline('x', '--body')])
      assertEquals(sourcesOf('exec gh issue comment 1 --body x'), [inline('x', '--body')])
    })

    it('finds gh after sudo with its options', () => {
      // Act & Assert
      assertEquals(sourcesOf('sudo -u root gh issue comment 1 --body x'), [inline('x', '--body')])
      assertEquals(sourcesOf('sudo -iu root -- gh issue comment 1 --body x'), [inline('x', '--body')])
    })

    it('finds gh inside a subshell without reading the closing parenthesis into the body', () => {
      // Act & Assert
      assertEquals(sourcesOf("(gh issue comment 1 --body 'x')"), [inline('x', '--body')])
    })

    it('finds gh inside a brace group', () => {
      // Act & Assert
      assertEquals(sourcesOf('{ gh issue comment 1 --body x; }'), [inline('x', '--body')])
    })

    it('finds gh inside a command substitution and backticks', () => {
      // Act & Assert
      assertEquals(sourcesOf('echo "$(gh issue comment 1 --body x)"'), [inline('x', '--body')])
      assertEquals(sourcesOf('echo `gh issue comment 1 --body x`'), [inline('x', '--body')])
    })

    it('finds gh after timeout with its options and duration', () => {
      // Act & Assert
      assertEquals(sourcesOf('timeout -s KILL --kill-after=5 30 gh issue comment 1 --body x'), [inline('x', '--body')])
    })

    it('finds gh after nohup, nice, stdbuf, setsid, and time -p', () => {
      // Act & Assert
      assertEquals(sourcesOf('nohup nice -n 5 stdbuf -oL setsid -f time -p gh issue comment 1 --body x'), [inline('x', '--body')])
    })

    it('finds gh inside a bash, sh, or zsh -c script', () => {
      // Act & Assert
      assertEquals(sourcesOf("bash -c 'gh issue comment 1 --body x'"), [inline('x', '--body')])
      assertEquals(sourcesOf('sh -c "gh issue comment 1 --body x"'), [inline('x', '--body')])
      assertEquals(sourcesOf("zsh -lc 'gh issue comment 1 --body x'"), [inline('x', '--body')])
    })

    it('reads the value of -o before -c rather than taking it for the script', () => {
      // Act & Assert
      assertEquals(sourcesOf('bash -o pipefail -c "gh issue comment 3 --body untagged"'), [inline('untagged', '--body')])
    })

    it('finds gh inside an eval', () => {
      // Act & Assert
      assertEquals(sourcesOf("eval 'gh issue comment 1 --body x'"), [inline('x', '--body')])
    })

    it('finds gh behind a reserved word', () => {
      // Act & Assert
      assertEquals(sourcesOf('if gh issue comment 1 --body x; then echo ok; fi'), [inline('x', '--body')])
    })

    it('finds gh behind an absolute path', () => {
      // Act & Assert
      assertEquals(sourcesOf('/usr/bin/gh pr comment 7 --body "text"'), [inline('text', '--body')])
    })

    it('ignores gh as an argument to another command', () => {
      // Act & Assert
      assertEquals(writesIn("echo gh issue create --body x && deno task test --body 'not a gh call'"), [])
    })

    it('ignores a shell that runs a script file rather than a -c string', () => {
      // Act & Assert
      assertEquals(writesIn('bash ./post.sh gh'), [])
    })
  })

  describe('findBodyWrites on gh run by xargs', () => {
    it('reads a body among the fixed arguments', () => {
      // Act & Assert
      assertEquals(sourcesOf('echo 4 | xargs -n 1 gh pr comment --body x'), [inline('x', '--body')])
    })

    it('blocks a body-writing command whose body would come from the input', () => {
      // Act
      const findings = writesIn("echo '--body x' | xargs gh pr comment 1")

      // Assert
      assertEquals(findings, [{ segment: 'xargs gh pr comment 1', subcommand: 'pr comment through xargs', sources: [runtime('', 'xargs')] }])
    })

    it('blocks gh whose subcommand would come from the input', () => {
      // Act & Assert
      assertEquals(sourcesOf('cat cmds | xargs gh'), [runtime('', 'xargs')])
    })

    it('marks a fixed body holding the replace string as built at run time', () => {
      // Act & Assert
      assertEquals(sourcesOf("ls | xargs -I {} gh pr comment 1 --body 'see {}'"), [{ kind: 'inline', value: 'see {}', flag: '--body', dynamic: true }])
    })

    it('ignores xargs running a gh command that writes no body', () => {
      // Act & Assert
      assertEquals(writesIn('echo 4 | xargs gh pr view'), [])
    })
  })

  describe('findBodyWrites on body files the script writes first', () => {
    it('reads the text a literal printf writes to the file', () => {
      // Act & Assert
      assertEquals(sourcesOf("printf 'hi\\n' > bodies/good2.md && gh pr comment 1 -F bodies/good2.md"), [written('hi\n', '-F')])
    })

    it('reads the text a quoted heredoc writes to the file through cat', () => {
      // Act & Assert
      assertEquals(sourcesOf("cat > bodies/reuse.md <<'EOF'\nuntagged\nEOF\ngh pr comment 1 -F bodies/reuse.md"), [written('untagged\n', '-F')])
    })

    it('reads the text echo writes, and joins an append onto a known write', () => {
      // Act & Assert
      assertEquals(sourcesOf(`echo Prose. > b.md && echo >> b.md && echo '${TAGLINE}' >> b.md && gh pr comment 1 -F b.md`), [written(`Prose.\n\n${TAGLINE}\n`, '-F')])
    })

    it('reads printf reusing its format for each argument', () => {
      // Act & Assert
      assertEquals(sourcesOf(`printf '%s\\n' 'Prose.' '' '${TAGLINE}' > b.md && gh pr comment 1 -F b.md`), [written(`Prose.\n\n${TAGLINE}\n`, '-F')])
    })

    it('reads a printf append onto the text the script wrote before it, decoding the escapes %b takes', () => {
      // Act & Assert
      assertEquals(sourcesOf(`printf '%s' 'Prose.' > b.md && printf '%b' '\\n\\n${TAGLINE}\\n' >> b.md && gh pr comment 1 -F b.md`), [written(`Prose.\n\n${TAGLINE}\n`, '-F')])
    })

    it('blocks a printf format holding a conversion other than %s or %b', () => {
      // Act & Assert
      assertEquals(sourcesOf("printf '%d\\n' 4 > b.md && gh pr comment 1 -F b.md"), [runtime('b.md', '-F')])
    })

    it('reads the text tee writes from the command piped into it', () => {
      // Act & Assert
      assertEquals(sourcesOf("printf 'hi\\n' | tee b.md && gh pr comment 1 -F b.md"), [written('hi\n', '-F')])
    })

    it('reads a written file copied onto the body file', () => {
      // Act & Assert
      assertEquals(sourcesOf('echo hi > a.md && cp a.md b.md && gh pr comment 1 -F b.md'), [written('hi\n', '-F')])
    })

    it('blocks a body file a command writes with output only running it would show', () => {
      // Act & Assert
      assertEquals(sourcesOf('git log -1 > b.md && gh pr comment 1 -F b.md'), [runtime('b.md', '-F')])
      assertEquals(sourcesOf('cat > b.md <<EOF\n$SHA\nEOF\ngh pr comment 1 -F b.md'), [runtime('b.md', '-F')])
    })

    it('blocks an append onto a file the script never wrote, and a copy of one', () => {
      // Act & Assert
      assertEquals(sourcesOf('echo hi >> b.md && gh pr comment 1 -F b.md'), [runtime('b.md', '-F')])
      assertEquals(sourcesOf('mv draft.md b.md && gh pr comment 1 -F b.md'), [runtime('b.md', '-F')])
    })

    it('blocks every body file after a write whose target is built at run time', () => {
      // Act & Assert
      assertEquals(sourcesOf('echo x > "$OUT" && gh pr comment 1 -F b.md'), [runtime('b.md', '-F')])
    })

    it('leaves a body file no earlier command writes to be read from disk', () => {
      // Act & Assert
      assertEquals(sourcesOf('echo x > other.md 2>&1 && gh pr comment 1 -F b.md'), [{ kind: 'file', value: 'b.md', flag: '-F', dynamic: false }])
    })

    it('matches a write and a read that name one file by different paths', () => {
      // Act & Assert
      assertEquals(sourcesOf('echo hi > /work/p/b.md && gh pr comment 1 -F ./b.md'), [written('hi\n', '-F')])
    })

    it('reads an input file the script writes as the JSON to check', () => {
      // Act & Assert
      assertEquals(sourcesOf(`echo '{"body":"x"}' > in.json && gh api repos/o/r/issues --input in.json`), [{ kind: 'written-json', value: '{"body":"x"}\n', flag: '--input', dynamic: false }])
    })
  })

  describe('findBodyWrites on directory changes', () => {
    it('reads a relative body file from the directory a literal cd moves to', () => {
      // Act & Assert
      assertEquals(sourcesOf('cd docs && gh pr comment 1 -F b.md'), [{ kind: 'file', value: 'docs/b.md', flag: '-F', dynamic: false }])
    })

    it('reads a relative body file from an absolute cd target', () => {
      // Act & Assert
      assertEquals(sourcesOf('cd /srv/x && gh pr comment 1 -F b.md'), [{ kind: 'file', value: '/srv/x/b.md', flag: '-F', dynamic: false }])
    })

    it('returns to the directory pushd left when popd runs', () => {
      // Act & Assert
      assertEquals(sourcesOf('pushd docs && popd && gh pr comment 1 -F b.md'), [{ kind: 'file', value: 'b.md', flag: '-F', dynamic: false }])
    })

    it('blocks a relative body file after a cd whose target is only known at run time', () => {
      // Act & Assert
      assertEquals(sourcesOf('cd "$DIR" && gh pr comment 1 -F b.md'), [runtime('b.md', '-F')])
      assertEquals(sourcesOf('cd && gh pr comment 1 -F b.md'), [runtime('b.md', '-F')])
      assertEquals(sourcesOf('popd && gh pr comment 1 -F b.md'), [runtime('b.md', '-F')])
    })

    it('keeps reading an absolute body file after a cd it cannot follow', () => {
      // Act & Assert
      assertEquals(sourcesOf('cd - && gh pr comment 1 -F /tmp/b.md'), [{ kind: 'file', value: '/tmp/b.md', flag: '-F', dynamic: false }])
    })

    it('matches a write made after a cd to the read of the same file', () => {
      // Act & Assert
      assertEquals(sourcesOf('cd docs && echo hi > b.md && cd .. && gh pr comment 1 -F docs/b.md'), [written('hi\n', '-F')])
    })
  })

  describe('issueEndpointPattern', () => {
    it('matches an issues, pulls, or releases endpoint, with or without a path after it', () => {
      // Act & Assert
      assertEquals(issueEndpointPattern.test('repos/o/r/issues/comments/5'), true)
      assertEquals(issueEndpointPattern.test('repos/o/r/pulls'), true)
      assertEquals(issueEndpointPattern.test('/repos/o/r/releases/1'), true)
    })

    it('matches a commit comment endpoint and an edit of one', () => {
      // Act & Assert
      assertEquals(issueEndpointPattern.test('repos/o/r/commits/abc123/comments'), true)
      assertEquals(issueEndpointPattern.test('repos/o/r/comments/7'), true)
    })

    it('refuses a commit endpoint that is not its comments', () => {
      // Act & Assert
      assertEquals(issueEndpointPattern.test('repos/o/r/commits/abc123/status'), false)
    })

    it('refuses another endpoint, which carries no issue, pull request, or release prose', () => {
      // Act & Assert
      assertEquals(issueEndpointPattern.test('repos/o/r/commits/abc'), false)
    })

    it('refuses a segment that only starts with issues, such as a differently named resource', () => {
      // Act & Assert
      assertEquals(issueEndpointPattern.test('repos/o/r/issues-archive'), false)
    })

    it('refuses a path broken by a newline, which no single word carries', () => {
      // Act & Assert
      assertEquals(issueEndpointPattern.test('repos/o\n/issues/1'), false)
    })
  })

  describe('graphqlBodyMutationPattern', () => {
    it('matches a mutation passing a body, across lines', () => {
      // Act & Assert
      assertEquals(graphqlBodyMutationPattern.test('mutation {\n  addComment(input: {subjectId: "x", body: $body}) { clientMutationId }\n}'), true)
    })

    it('refuses a query that only reads a body field', () => {
      // Act & Assert
      assertEquals(graphqlBodyMutationPattern.test('query { repository(name: "r") { issue(number: 1) { body } } }'), false)
    })

    it('refuses a mutation with no body argument', () => {
      // Act & Assert
      assertEquals(graphqlBodyMutationPattern.test('mutation { closeIssue(input: {issueId: "x"}) { clientMutationId } }'), false)
    })
  })

  describe('shellCommandFlagPattern', () => {
    it('matches -c alone or inside a cluster', () => {
      // Act & Assert
      assertEquals(shellCommandFlagPattern.test('-c'), true)
      assertEquals(shellCommandFlagPattern.test('-lc'), true)
    })

    it('refuses a long option and a cluster without c', () => {
      // Act & Assert
      assertEquals(shellCommandFlagPattern.test('--command'), false)
      assertEquals(shellCommandFlagPattern.test('-ex'), false)
    })

    it('refuses an option followed by a newline', () => {
      // Act & Assert
      assertEquals(shellCommandFlagPattern.test('-c\n'), false)
    })
  })

  describe('taglineSeparatorPattern', () => {
    it('matches a blank line, including one holding spaces', () => {
      // Act & Assert
      assertEquals(taglineSeparatorPattern.test('Prose.\n\n'), true)
      assertEquals(taglineSeparatorPattern.test('Prose.\n  \n'), true)
    })

    it('refuses a single line break, which leaves no blank line', () => {
      // Act & Assert
      assertEquals(taglineSeparatorPattern.test('Prose.\n'), false)
    })

    it('refuses text on the line before the tagline', () => {
      // Act & Assert
      assertEquals(taglineSeparatorPattern.test('Prose.\n\nmore '), false)
    })
  })
})
